(()=>{'use strict';
const exact=new Map(Object.entries({
'ETHICS EXPERIENCE':'تجربة الأخلاقيات',
'ETHICS IN YARAANI':'الأخلاقيات في يرعاني',
'PATIENT STATUS':'حالة المريض',
'HEART RATE':'معدل نبض القلب',
'78 BPM':'78 نبضة/دقيقة',
'SECURE DATA':'بيانات محمية',
'Protected ✓':'محمي ✓',
'CARE PROVIDER':'مقدم الرعاية',
'Verified ✓':'موثّق ✓',
'01 · HUMAN FIRST':'01 · الإنسان أولًا',
'PATIENT CARE JOURNEY':'رحلة رعاية المريض',
'Yara Bot يقترح فقط':'يارا بوت يقترح فقط',
'AI suggests · Human decides':'الذكاء الاصطناعي يقترح · الإنسان يقرر',
'02 · JOURNEY':'02 · رحلة الرعاية',
'THE ETHICAL QUESTION':'السؤال الأخلاقي',
'03 · RESPONSIBILITY':'03 · المسؤولية',
'ETHICAL FRAMEWORK':'الإطار الأخلاقي',
'YARAANI':'يرعاني',
'Human-centered ethics':'أخلاقيات تتمحور حول الإنسان',
'04 · PRINCIPLES':'04 · المبادئ',
'PRIVACY BY DESIGN':'الخصوصية في صميم التصميم',
'MEDICAL RECORD':'السجل الصحي',
'Protected Patient Data':'بيانات المريض المحمية',
'Synthetic Data':'بيانات اصطناعية',
'Role Separation':'فصل الصلاحيات',
'Need-to-Know':'الوصول حسب الحاجة',
'Minimum Exposure':'أقل كشف ممكن',
'05 · PRIVACY':'05 · الخصوصية',
'SECURITY & ACCESS CONTROL':'الأمن والتحكم في الوصول',
'USER':'المستخدم',
'Requesting access':'طلب وصول',
'Identity':'الهوية',
'Authentication':'التحقق من الهوية',
'Role':'الدور',
'Permission':'الصلاحية',
'ACCESS GRANTED':'تم السماح بالوصول',
'Unauthorized Attempt':'محاولة غير مصرح بها',
'ACCESS DENIED':'تم رفض الوصول',
'CORE PRINCIPLE':'المبدأ الأساسي',
'LEAST PRIVILEGE':'أقل صلاحية ممكنة',
'06 · SECURITY':'06 · الأمن',
'HUMAN IN THE LOOP':'الإنسان داخل دائرة القرار',
'AI':'ذكاء اصطناعي',
'YARA BOT':'يارا بوت',
'AI Suggestion':'اقتراح الذكاء الاصطناعي',
'FINAL DECISION':'القرار النهائي',
'Responsible Action':'إجراء مسؤول',
'07 · HUMAN DECISION':'07 · القرار البشري',
'TRANSPARENCY & INFORMED USE':'الشفافية والاستخدام الواعي',
'YARA BOT · SUGGESTION':'يارا بوت · اقتراح',
'Confidence 86%':'درجة الثقة 86%',
'Suggestion':'اقتراح',
'MD':'طبيب',
'Diagnosis':'تشخيص',
'Overtrust':'ثقة مفرطة',
'Misunderstanding':'سوء فهم',
'Blind Dependence':'اعتماد أعمى',
'→ Transparency':'→ الشفافية',
'08 · TRANSPARENCY':'08 · الشفافية',
'SAFETY FIRST':'السلامة أولًا',
'RED FLAG':'إشارة خطر',
'Emergency signal detected':'تم اكتشاف إشارة طارئة',
'Detect':'اكتشاف',
'Stop':'إيقاف',
'Warn':'تحذير',
'Emergency':'طوارئ',
'09 · SAFETY':'09 · السلامة',
'✓ VERIFIED':'✓ موثّق',
'HEALTHCARE PROVIDER':'مقدم رعاية صحية',
'HEALTHCARE PROVIDER VERIFICATION':'التحقق من مقدم الرعاية الصحية',
'Qualification':'المؤهل',
'Experience':'الخبرة',
'Professional Data':'البيانات المهنية',
'Manager Review':'مراجعة المدير',
'VERIFIED':'موثّق',
'Eligible for Patient Assignment →':'مؤهل لإسناد المرضى ←',
'10 · VERIFICATION':'10 · التحقق',
'MEDICAL RECORD · #YR-1048':'السجل الصحي · #YR-1048',
'VISIT CLOSED':'أُغلقت الزيارة',
'RECORD LOCKED':'تم قفل السجل',
'Original history preserved':'تم الحفاظ على السجل الأصلي',
'DATED CORRECTION ADDENDUM':'ملحق تصحيح مؤرخ',
'INTEGRITY & ACCOUNTABILITY':'النزاهة والمساءلة',
'Request Status':'حالة الطلب',
'Assignment':'الإسناد',
'Provider Acceptance':'قبول مقدم الرعاية',
'Visit Start':'بداية الزيارة',
'Documentation':'التوثيق',
'Record Locked':'قفل السجل',
'11 · INTEGRITY':'11 · النزاهة',
'RELIABILITY & ACCESSIBILITY':'الموثوقية وسهولة الوصول',
'SYSTEM RELIABILITY':'موثوقية النظام',
'SAFE FAILURE':'فشل آمن',
'Yara Bot Offline?':'هل يارا بوت غير متصل؟',
'Manual workflow continues':'يستمر المسار اليدوي',
'External Service Failure?':'هل تعطلت خدمة خارجية؟',
'Core system remains available':'يبقى النظام الأساسي متاحًا',
'Video Interrupted?':'هل انقطعت الاستشارة المرئية؟',
'Retry / Reschedule':'إعادة المحاولة / إعادة الجدولة',
'AI OFFLINE':'الذكاء الاصطناعي غير متصل',
'CARE CONTINUES':'الرعاية مستمرة',
'ACCESSIBILITY & FAIR ACCESS':'سهولة الوصول والعدالة في الاستخدام',
'12 · ACCESS':'12 · سهولة الوصول',
'ETHICS ACROSS THE PATIENT JOURNEY':'الأخلاقيات عبر رحلة المريض',
'PRIVACY':'الخصوصية',
'RESPONSIBLE AI':'ذكاء اصطناعي مسؤول',
'HUMAN DECISION':'قرار بشري',
'SAFETY':'السلامة',
'INTEGRITY':'النزاهة',
'CONTINUITY':'استمرارية الرعاية',
'13 · COMPLETE SYSTEM':'13 · النظام المتكامل',
'FINAL THOUGHT':'الفكرة الختامية',
'HUMAN FIRST. TECHNOLOGY IN SERVICE OF PEOPLE.':'الإنسان أولًا، والتقنية في خدمته.',
'14 · HUMAN FIRST':'14 · الإنسان أولًا',
'↑ ↓ SLIDES   ·   ← → CONTENT':'↑ ↓ الشرائح   ·   ← → المحتوى',
'داخل السلايد':'داخل الشريحة'
}));
const partial=[
['PENDING VERIFICATION','قيد التحقق'],['Identity & Documents','الهوية والوثائق'],['Qualification Review','مراجعة المؤهل'],['Experience Check','التحقق من الخبرة'],['Manager Approval','اعتماد المدير'],['NORMAL FLOW','المسار الطبيعي'],['Booking → Care','الحجز ← الرعاية'],['DETECT → STOP','اكتشاف ← إيقاف'],['WARN','تحذير'],['EMERGENCY','طوارئ'],['AUDIT TRAIL','سجل التدقيق'],['Appointment','الموعد'],['Patient Rating','تقييم المريض'],['Original + Addendum','الأصل + ملحق التصحيح'],['Accessible Care','رعاية سهلة الوصول'],['TELEMEDICINE','الرعاية عن بُعد'],['Connected Care','رعاية متصلة'],['HUMAN FIRST','الإنسان أولًا']
];
function localizeTextNode(n){const raw=n.nodeValue;if(!raw||!raw.trim())return;const t=raw.trim();if(exact.has(t)){n.nodeValue=raw.replace(t,exact.get(t));return}let v=raw;for(const [a,b] of partial)v=v.split(a).join(b);n.nodeValue=v}
function localize(root=document.body){
 const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||['SCRIPT','STYLE','NOSCRIPT'].includes(p.tagName))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});
 const nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(localizeTextNode);
 document.documentElement.lang='ar';document.documentElement.dir='rtl';document.body.dir='rtl';
 document.querySelectorAll('.brand>i,.brand-symbol').forEach(el=>{if(el.textContent.trim()==='Y')el.textContent='ي'});
 document.querySelectorAll('.center').forEach(el=>{if(el.childNodes[0]&&el.childNodes[0].nodeType===3&&el.childNodes[0].nodeValue.trim()==='Y')el.childNodes[0].nodeValue='ي'});
 document.querySelectorAll('[aria-label]').forEach(el=>{let a=el.getAttribute('aria-label');if(!a)return;for(const [x,y] of exact)a=a.split(x).join(y);el.setAttribute('aria-label',a)});
}
localize();
const obs=new MutationObserver(ms=>{for(const m of ms){m.addedNodes.forEach(n=>{if(n.nodeType===1)localize(n);else if(n.nodeType===3)localizeTextNode(n)})}});obs.observe(document.body,{childList:true,subtree:true});
})();